// <auto-generated />
namespace Microbrewit.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SpargeStepHopFirstWort : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpargeStepHopFirstWort));
        
        string IMigrationMetadata.Id
        {
            get { return "201503120624259_SpargeStepHop-FirstWort"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
